version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - chatbot_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  python_client:
    build: .
    container_name: python_client_container
    depends_on:
      - redis
    networks:
      - chatbot_network
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  chatbot_network:
    driver: bridge

volumes:
  redis_data: